// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiZvdZfaV9P2XdXzkVGvpv2nIEZPPeBBg',
    appId: '1:765154562260:web:6f980f2802477716fb6b41',
    messagingSenderId: '765154562260',
    projectId: 'creature-comforts-a5aaa',
    authDomain: 'creature-comforts-a5aaa.firebaseapp.com',
    storageBucket: 'creature-comforts-a5aaa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy52HDaOlXa2BZJnXDXj-0Akqm_0h4BuA',
    appId: '1:765154562260:android:83525f6786573d4ffb6b41',
    messagingSenderId: '765154562260',
    projectId: 'creature-comforts-a5aaa',
    storageBucket: 'creature-comforts-a5aaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAV-dsRlCdeYTi4YY-AEQhgwAYa02qiZkY',
    appId: '1:765154562260:ios:5ec6f4c6b8a572d8fb6b41',
    messagingSenderId: '765154562260',
    projectId: 'creature-comforts-a5aaa',
    storageBucket: 'creature-comforts-a5aaa.firebasestorage.app',
    iosBundleId: 'com.icodeforyou.creatureComforts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAV-dsRlCdeYTi4YY-AEQhgwAYa02qiZkY',
    appId: '1:765154562260:ios:5ec6f4c6b8a572d8fb6b41',
    messagingSenderId: '765154562260',
    projectId: 'creature-comforts-a5aaa',
    storageBucket: 'creature-comforts-a5aaa.firebasestorage.app',
    iosBundleId: 'com.icodeforyou.creatureComforts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiZvdZfaV9P2XdXzkVGvpv2nIEZPPeBBg',
    appId: '1:765154562260:web:4d1e4c3fd0d24f15fb6b41',
    messagingSenderId: '765154562260',
    projectId: 'creature-comforts-a5aaa',
    authDomain: 'creature-comforts-a5aaa.firebaseapp.com',
    storageBucket: 'creature-comforts-a5aaa.firebasestorage.app',
  );
}
