name: startup_demo
description: "Demo For starting up and themes"
publish_to: 'none'
version: 0.0.1
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  animated_rail_menu: ^0.9.0
  animated_widgets: ^0.0.1
  application_startup: ^0.0.5
  extensions: ^1.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1

  gap: ^3.0.1
  get_it: ^9.2.1
  go_router: ^17.1.0
  my_logger:
    path: ../../packages/my_logger
  random_color_generator:
    path: ../../packages/random_color_generator
  remind_me:
    path: ../../packages/remind_me
  service_locator:
    path: ../../packages/service_locator
  since_when:
    path: ../../packages/since_when
  since_when_widgets:
    path: ../../packages/since_when_widgets
  status_bar_chameleon:
    path: ../../plugins/status_bar_chameleon
  theme_manager:
    path: ../../packages/theme_manager
  theme_service:
    path: ../../packages/theme_service
  theme_widget:
    path: ../../packages/theme_widget

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
