name: startup_demo
description: "Demo For starting up and themes"
publish_to: 'none'
version: 0.0.1
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  application_setup:
    path: ../../packages/application_setup
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  gap: ^3.0.1
  get_it: ^9.2.1
  theme_manager:
    path: ../../packages/theme_manager
  theme_selection_widget:
    path: ../../packages/theme_selection_widget

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
