name: rail_navigation
description: "A flutter package to create navigation rail apps"
publish_to: none
homepage:
resolution: workspace

environment:
  sdk: ">=3.12.0 <4.0.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  icodeforyou_lints: ^1.0.0

flutter:
  uses-material-design: true
