name: rail_navigation
description: "A flutter package to create navigation rail apps"
publish_to: none
homepage:
resolution: workspace
version: 1.0.0

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  extensions: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  icodeforyou_lints: ^1.0.0

flutter:
  uses-material-design: true
