# packages/sincewhen_drift_framework/analysis_options.yaml
analyzer:
  errors:
    use_super_parameters: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:icodeforyou_lints/analysis_options.yaml