# packages/app_preferences/analysis_options.yaml
analyzer:
  errors:
    avoid_positional_boolean_parameters: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:icodeforyou_lints/analysis_options.yaml