name: settings_widget
description: Adaptive settings modal for Flutter apps.
version: 0.0.3
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
