# packages/since_when_widgets/analysis_options.yaml
analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:icodeforyou_lints/analysis_options.yaml
