name: since_when_widgets
description: A Flutter widget for displaying SQLite query results in a spreadsheet-style view.
version: 1.0.1+1
resolution: workspace
publish_to: "none"

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  extensions: ^1.0.1
  flutter:
    sdk: flutter
  random_color_generator: ^1.0.0
  since_when: 0.0.1+100

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true