# packages/sincewhen_screens/pubspec.yaml
name: sincewhen_screens
description: "Edit screen for a sincewhen record"
publish_to: none
resolution: workspace
version: 1.0.0

environment:
  sdk: ^3.12.0

dependencies:
  custom_widgets: ^1.0.0
  equatable: ^2.1.0
  extensions: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  gap: ^3.0.1
  intl: ^0.20.3
  scrolling_datetime_pickers: ^1.0.0
  sincewhen_models: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  icodeforyou_lints: ^1.0.0