name: biometric_gate_service_local
description: Local implementation of BiometricGateService using local_auth and flutter_secure_storage.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  biometric_gate_service: ^1.0.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^10.0.0
  fpdart: ^1.2.0
  local_auth: ^3.0.1
  meta: ^1.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.5
  very_good_analysis: ^10.2.0
