name: ice_chips
description: For tags stored in since_when with just a collection of selected items
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  extensions: ^1.0.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  fpdart: ^1.1.0
  since_when_framework: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
