# icodeforyou_flutter/packages/since_when/analysis_options.yaml

include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    avoid_redundant_argument_values: ignore
    avoid_types_on_closure_parameters: ignore
    document_ignores: ignore
    lines_longer_than_80_chars: ignore
    omit_local_variable_types: ignore
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'

linter:
  rules:
    # Relaxed rules if needed (none for now - keeping strict)