name: sqlite_viewer
description: A Flutter widget for displaying SQLite query results in a spreadsheet-style view.
version: 1.0.0+1
resolution: workspace
publish_to: "none"

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.5"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true