name: sqlite_viewer
description: A Flutter widget for displaying SQLite query results in a spreadsheet-style view.
version: 1.0.0+1
resolution: workspace
publish_to: "none"

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  dartz: ^0.10.1
  edittext_popover:
    path: ../edittext_popover
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  sqflite: ^2.4.2
  theme_package:
    path: ../theme_package

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
