include: package:very_good_analysis/analysis_options.yaml

analyzer:
  errors:
    always_use_package_imports: ignore
    avoid_redundant_argument_values: ignore
    comment_references: ignore
    depend_on_referenced_packages: ignore
    omit_local_variable_types: ignore
    public_member_api_docs: ignore

  exclude:
    - '**/*.config.dart'
    - '**/*.directories.dart'
    - '**/*.freezed.dart'
    - '**/*.g.dart'
    - '**/*.gen.dart'
    - '**/*.mocks.dart'

linter:
  rules:
    # Relaxed rules if needed (none for now - keeping strict)
