name: widgetbook_workspace
description: "Flutter widget book"
publish_to: 'none'
version: 0.1.1
resolution: workspace

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  adaptive_modal:
    path: ../../packages/adaptive_modal
  analog_clock_widget:
    path: ../../packages/analog_clock_widget
  animated_checkbox_widget:
    path: ../../packages/animated_checkbox_widget
  edittext_popover:
    path: ../../packages/edittext_popover
  extensions:
    path: ../../packages/extensions
  flutter_bloc: ^9.1.1
  scrolling_datetime_pickers:
    path: ../../packages/scrolling_datetime_pickers
  random_color_generator:
    path: ../../packages/random_color_generator
  since_when:
    path: ../../packages/since_when
  sqlite_viewer:
    path: ../../packages/sqlite_viewer
  startup_package:
    path: ../../packages/startup_package
  step_slider_package:
    path: ../../packages/step_slider_package
  theme_package:
    path: ../../packages/theme_package
  widgetbook: ^3.22.0
  widgetbook_annotation: ^3.11.0

dev_dependencies:
  build_runner: ^2.7.0   # dart run build_runner build --delete-conflicting-outputs
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0
  mockito: ^5.5.1
  widgetbook_generator: ^3.22.0


flutter:
  uses-material-design: true
