name: theme_package
description: "A new Flutter package project."
version: 0.0.1
resolution: workspace
publish_to: "none"

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  fpdart: ^1.2.0
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true