// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuxNL663qH8nsMWVAyQV9-kVMKiqpg90k',
    appId: '1:452190445233:web:f0317e9e209b7f9fd78c90',
    messagingSenderId: '452190445233',
    projectId: 'edgewaterhomeapp',
    authDomain: 'edgewaterhomeapp.firebaseapp.com',
    storageBucket: 'edgewaterhomeapp.firebasestorage.app',
    measurementId: 'G-3NVCKPWKG8',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuxNL663qH8nsMWVAyQV9-kVMKiqpg90k',
    appId: '1:452190445233:web:f0317e9e209b7f9fd78c90',
    messagingSenderId: '452190445233',
    projectId: 'edgewaterhomeapp',
    authDomain: 'edgewaterhomeapp.firebaseapp.com',
    storageBucket: 'edgewaterhomeapp.firebasestorage.app',
    measurementId: 'G-3NVCKPWKG8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCclCvfn5znIxGEiVoAICRuzTOBO4sSTeM',
    appId: '1:452190445233:ios:64ee9ac00b0d6a39d78c90',
    messagingSenderId: '452190445233',
    projectId: 'edgewaterhomeapp',
    storageBucket: 'edgewaterhomeapp.firebasestorage.app',
    iosBundleId: 'com.icodeforyou.dogfeeding.edgewaterDogFeeding',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCclCvfn5znIxGEiVoAICRuzTOBO4sSTeM',
    appId: '1:452190445233:ios:64ee9ac00b0d6a39d78c90',
    messagingSenderId: '452190445233',
    projectId: 'edgewaterhomeapp',
    storageBucket: 'edgewaterhomeapp.firebasestorage.app',
    iosBundleId: 'com.icodeforyou.dogfeeding.edgewaterDogFeeding',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6k76wB_XHD2IQXEOQuoxEk_Krjz7_VDo',
    appId: '1:452190445233:android:1b3ed66322f28c95d78c90',
    messagingSenderId: '452190445233',
    projectId: 'edgewaterhomeapp',
    storageBucket: 'edgewaterhomeapp.firebasestorage.app',
  );

}