name: theme_manager
description: "A new Flutter package project."
version: 1.0.0
resolution: workspace
publish_to: "none"

environment:
  sdk: ">=3.12.0 <4.0.0"
  
dependencies:
  animated_widgets: ^1.0.0
  app_preferences: ^1.0.0
  app_preferences_service: ^1.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  my_logger: ^1.0.0
  service_locator: ^1.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.3.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true