# pubspec.yaml - theme_manager
name: theme_manager
description: "Flutter package control/manager light and dark themes"
version: 0.0.1
resolution: workspace
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.2"

dependencies:
  extensions:
    path: ../extensions
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  gap: ^3.0.1
  nosql:
    path: ../nosql

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
