# pubspec.yaml analog_clock_widget
# Minimal dependencies for abstractions packagename: analog_clock_widget

name: analog_clock_widget
description: "Package to handle all abstract classes"
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  abstractions: ^0.1.1
  extensions: ^1.0.1
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true