name: custom_widgets
description: A collection of custom widgets I use often
version: 1.0.0
resolution: workspace
publish_to: none

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  analog_clock_widget: ^1.0.0
  equatable: ^2.1.0
  extensions: ^1.0.4
  flutter:
    sdk: flutter
  flutter_bloc: 9.1.1
  gap: ^3.0.1
  go_router: ^17.1.0
  google_fonts: ^8.2.1
  platform_utils: ^1.0.0
  status_bar_chameleon: ^1.0.0
  theme_manager: ^1.0.0

dev_dependencies:
  bloc_test: ^10.0.0
  flutter_test:
    sdk: flutter
  icodeforyou_lints: ^1.0.0

flutter:
  uses-material-design: true