# packages/sincewhen_models/pubspec.yaml
name: sincewhen_models
description: "Pure Dart classes for sincewhen_framework"
publish_to: none
resolution: workspace
version: 1.0.0

environment:
  sdk: ^3.12.0

dependencies:
  equatable: ^2.1.0
  extensions: ^1.0.4
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  icodeforyou_lints: ^1.0.0