# pubspec.yaml - nosql
name: nosql
description: "Flutter package to use fast no-sql"
version: 0.0.1
resolution: workspace
publish_to: none

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.5"

dependencies:
  flutter:
    sdk: flutter
  hive_ce: ^2.11.3
  hive_ce_flutter: ^2.3.2
  mocktail: ^1.0.4
  path: ^1.9.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  path_provider_platform_interface: ^2.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
