# packages/mypickdf/pubspec.yaml
name: mypickdf
description: "Picker Preview"
publish_to: none
resolution: workspace
version: 1.0.0

environment:
  sdk: ^3.12.0

dependencies:
  datetime_popover_pickers: ^1.0.0
  extensions: ^1.0.4
  flutter:
    sdk: flutter
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  icodeforyou_lints: ^1.0.0