name: application_startup
description: "A template for applications with splash screen and theme"
publish_to: none
homepage:
resolution: workspace
version: 1.0.0

environment:
  sdk: ">=3.12.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  splash_framework: ^1.0.0
  theme_framework: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  icodeforyou_lints: ^1.0.0

flutter:
  uses-material-design: true