analyzer:
  errors:
    no_runtimetype_tostring: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:icodeforyou_lints/analysis_options.yaml