# packages/archetypes/pubspec.yaml
name: archetypes
description: "Mason template for creating packages"
publish_to: none
resolution: workspace
version: 1.0.0

environment:
  sdk: ^3.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  icodeforyou_lints: ^1.0.0