# packages/extensions/analysis_options.yaml
analyzer:
  errors:
    deprecated_consistency: ignore
  exclude:
    - build/**
    - android/**
    - ios/**
    - web/**
    - windows/**
    - macos/**
    - linux/**
include: package:icodeforyou_lints/analysis_options.yaml
