# analysis_options.yaml
include: package:very_good_analysis/analysis_options.yaml

linter:
  rules:
    public_member_api_docs: false

analyzer:
  errors:
    document_ignores: ignore
  exclude:
    - '**/*.g.dart'
    - '**/*.freezed.dart'