name: stacking_widgets
description: Stacks an array of 'Piled Widgets' on a stack for bubble effect
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=3.24.0"

resolution: workspace
dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0
