name: iOS

on:
  pull_request:
    paths:
      - "plugins/**/ios/**"
      - "packages/**/ios/**"

jobs:
  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Lint iOS podspecs
        run: |
          find plugins packages -name "*.podspec" | while read podspec; do
            echo "Linting $podspec"
            pod lib lint "$podspec" --allow-warnings
          done
