name: Main Branch CI

on:
  push:
    branches:
      - main
    paths:
      - "packages/**"
      - "plugins/**"
      - ".github/workflows/main_ci.yml"
      - "melos.yaml"
      - "pubspec.yaml"
      - "**/pubspec.yaml"

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    outputs:
      packages: ${{ steps.filter.outputs.packages }}
      plugins: ${{ steps.filter.outputs.plugins }}
    steps:
      - uses: actions/checkout@v4

      # Detect which packages/plugins changed
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            packages:
              - 'packages/**'
            plugins:
              - 'plugins/**'

  test_packages:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.packages == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
      - name: Run package tests
        run: |
          melos bootstrap
          melos run test --scope="packages/*"

  test_plugins:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.plugins == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - name: Install dependencies
        run: dart pub get
      - name: Run plugin tests
        run: |
          melos bootstrap
          melos run test --scope="plugins/*"
