# packages/{{name.snakeCase()}}/pubspec.yaml
name: {{name.snakeCase()}}
description: "{{description}}"
publish_to: none
resolution: workspace
version: 1.0.0

environment:
  sdk: ^3.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  icodeforyou_lints: ^1.0.0