name: service_locator
description: "Package to Manage Services that have dependencies"
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: ">=3.11.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  gap: ^3.0.1
  get_it: ^9.2.1
  my_logger:
    path: ../my_logger

 

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^10.2.0

flutter:
  uses-material-design: true
